### PR TITLE
[issue-160] Fix Slack Incompatibility Error

### LINKED ISSUE #160: Slack alerts error
Hi, I get an error when the heuristic alerts to slack, which makes `pessimism_alerts_generated_total` metric doesn't work.

Found that, the response from slack is just a plain text "ok" or some error message like "channel not found", not a struct as below.
https://github.com/base-org/pessimism/blob/14481ced518b71995bac5b617f971ea9aaee367c/internal/client/slack.go#L77-L80

Could you please fix this issue? Pessimism works well for me.😀

### PR DESCRIPTION
**Pull request by epociask**
#  Fix Slack Incompatibility Error

## Fixes Issue #160 

Fixes #160 

## Changes proposed
* Updated slack client logic to handle unstructured success response payloads
* Updated alerting documentation with guides on adding a slack webhook to Pessimism
* Updated mock slack server in E2E framework to randomly return different payload types

### CODE REVIEW

File: internal/client/slack.go [hunk 1]
```diff
@@ -120,15 +120,29 @@ func (sc slackClient) PostEvent(ctx context.Context, event *AlertEventTrigger) (
...
 		return nil, err
 	}
 
+	// 3.b. validate status code
+	if resp.StatusCode != http.StatusOK {
+		return nil, fmt.Errorf("slack API returned bad status code %d", resp.StatusCode)
+	}
+
+	// 3.c. validate response body
+	if string(bytes) == "ok" {
```
Comment (adrain-cb) [inline internal/client/slack.go:135]: [nit] Using a const for slack Ok status might be better here

Comment (epociask) [reply internal/client/slack.go]: [6e20b7d](https://github.com/base-org/pessimism/pull/173/commits/6e20b7d993c03f8d627fa675659949f6b701b67c)

**Review by adrain-cb — APPROVED** [review]
lgtm
