### PR TITLE
Issue 6 fix

### LINKED ISSUE #6: GETH Block Oracle Definition Logic is Bug Prone and Untested
## Problem
As noted in [Initial Pipeline PR](https://github.com/base-org/pessimism/pull/3), the oracle implementation for indexing sequential block metadata from an [op-geth](https://github.com/ethereum-optimism/op-geth) execution node is incredibly lackluster and could use some heavy refinements to ensure better resiliency/extensibility.

## Proposed Solution
The following improvements should be supported to better enhance the oracle definition:
1. A backtest routine should be supported by the Oracle definition that takes a starting and ending block height parameter to then sequentially iterate from `block_start` to `block_end` inclusively; reading each block before transiting it to downstream components.
_NOTE:_ Batched concurrent processing techniques could be leveraged here to ensure more efficient backtesting. 

2. Failure cases should be threat modeled with engineered fail safe solutions. Some of these cases have been noted in the _internal/conduit/registry/geth_block.go_ file. However there are likely more that aren't currently considered. 

3. All oracle definition logic should be fully unit tested; this includes validating happy path logic as well as ensuring that fail safe routines behave as expected. 
 
_NOTE:_ The `ethClient` struct could be binded to some internal interface so that failure cases can be properly unit tested. 

## Resources
- [Initial Pipeline PR](https://github.com/base-org/pessimism/pull/3)
- [OP Indexer](https://github.com/ethereum-optimism/optimism/tree/develop/indexer) --> Great point of reference

### PR DESCRIPTION
**Pull request by anupsv-cb**
## Fixes Issue
Closes #6 

## Changes proposed
1. Added goroutine management and "close" functions to be used for proper management of goroutines.
2. Added backtest functions
3. Added functionality of start and end heights, along with retries with editable config for number of retries.

## Note to reviewers
Some changes can be made to improve, but leaving that for now since more structure of the project will define how to changes need to be made.

### CODE REVIEW

File: internal/conduit/pipeline/eth_client.go [hunk 1]
```diff
@@ -0,0 +1,38 @@
+package pipeline
+
```
Comment (epociask) [inline internal/conduit/pipeline/eth_client.go:2]: Let's create a low priority issue for a RetryableEthClient

Comment (epociask) [reply internal/conduit/pipeline/eth_client.go:2]: Also introduce idiomatic constructor patterns as well

File: internal/conduit/pipeline/oracle.go [hunk 2]
```diff
@@ -58,14 +63,21 @@ func NewOracle(ctx context.Context, ot OracleType,
 	return o, nil
 }
 
+func (o *Oracle) Close() {
+	log.Printf("Waiting for oracle goroutines to be done.")
+	o.waitGroup.Wait()
+	log.Printf("Oracle goroutines have exited.")
+}
```
Comment (epociask) [inline internal/conduit/pipeline/oracle.go:70]: Let's create an issue to fix this closure logic and add closures for all component types

File: internal/conduit/pipeline/types.go [hunk 3]
```diff
@@ -26,7 +26,8 @@ const (
 // Generalized component constructor types
 type (
 	// OracleConstructor ... Type declaration that a registry oracle component constructor must adhere to
-	OracleConstructor = func(ctx context.Context, ot OracleType, cfg *config.OracleConfig) (Component, error)
+	OracleConstructor = func(ctx context.Context, ot OracleType, cfg *config.OracleConfig,
+		clientNew EthClientInterface) (Component, error)
```
Comment (epociask) [inline internal/conduit/pipeline/types.go]:
```suggestion
		ec EthClientInterface) (Component, error)
```

File: internal/conduit/registry/geth_block.go [hunk 4]
```diff
@@ -18,81 +20,207 @@ const (
 
 // GethBlockODef ...GethBlock register oracle definition used to drive oracle component
 type GethBlockODef struct {
-	cfg *config.OracleConfig
-	// TODO - Bind this to an interface and mock so that this logic can be tested
-	client *ethclient.Client
-
-	currHeight *big.Int
+	cfg             *config.OracleConfig
+	clientInterface pipeline.EthClientInterface
```
Comment (epociask) [inline internal/conduit/registry/geth_block.go:24]:
```suggestion
	client pipeline.EthClientInterface
```

File: internal/conduit/registry/geth_block.go [hunk 5]
```diff
@@ -18,81 +20,207 @@ const (
...
 
 // BackTestRoutine ...
-func (oracle *GethBlockODef) BackTestRoutine(_ context.Context, _ chan models.TransitData) error {
-	// TODO - implement
+func (oracle *GethBlockODef) BackTestRoutine(ctx context.Context, componentChan chan models.TransitData,
+	startHeight *big.Int, endHeight *big.Int) error {
+	if endHeight.Cmp(startHeight) < 0 {
+		return errors.New("start height cannot be more than the end height")
+	}
+
```
Comment (epociask) [inline internal/conduit/registry/geth_block.go:57]: `Edge case:` What if the start height is greater than the current height?

File: internal/conduit/registry/geth_block.go [hunk 6]
```diff
@@ -18,81 +20,207 @@ const (
...
+			log.Printf("Header Retry number: %d", i)
+			time.Sleep(time.Duration(i) * time.Second)
+		}
+
+		header, err := oracle.clientInterface.HeaderByNumber(ctx, height)
+		if err != nil {
+			log.Printf("Header fetching error: %s", err.Error())
+		} else {
+			return header
+		}
```
Comment (epociask) [inline internal/conduit/registry/geth_block.go:129]:
```suggestion
		if err == nil {
		   return header
		}
		log.Printf("Header fetching error: %s", err.Error())
```

File: internal/conduit/registry/geth_block.go [hunk 7]
```diff
@@ -18,81 +20,207 @@ const (
...
+
+		if i == oracle.cfg.NumOfRetries {
+			log.Printf("All retries exhausted. Block at height %d will be skipped", height)
+			return nil
```
Comment (epociask) [inline internal/conduit/registry/geth_block.go:133]:
```suggestion
```

File: internal/conduit/registry/geth_block.go [hunk 8]
```diff
@@ -18,81 +20,207 @@ const (
...
+	// NOTE - Might need improvements in future as the project takes shape.
 
-	ticker := time.NewTicker(pollInterval * time.Millisecond)
+	if oracle.cfg.EndHeight != nil && oracle.cfg.StartHeight == nil {
+		return errors.New("cannot start with latest block height with end height configured")
+	}
+
+	if oracle.cfg.EndHeight.Cmp(oracle.cfg.StartHeight) < 0 {
+		return errors.New("start height cannot be more than the end height")
+	}
```
Comment (epociask) [inline internal/conduit/registry/geth_block.go:175]: Note that this should be changed in the future where these validations happen during Oracle construction so that pipelines are built out to then be invalidated

File: internal/conduit/registry/geth_block.go [hunk 9]
```diff
@@ -18,81 +20,207 @@ const (
...
+
+			height := oracle.getHeightToProcess()
+
+			// TODO: potentially break this functions off with the right context.
+			header := oracle.fetchHeaderWithRetry(ctx, height)
+
+			// means the above retries failed
+			if header == nil {
 				continue
 			}
```
Comment (epociask) [inline internal/conduit/registry/geth_block.go:198]: Let's loggg here

File: internal/conduit/registry/geth_block.go [hunk 10]
```diff
@@ -18,81 +20,207 @@ const (
...
 
-			block, err := oracle.client.BlockByNumber(ctx, header.Number)
-			if err != nil {
-				// log.Printf("Error fetching block @ height %d: %s", height, err)
+			block := oracle.fetchBlockWithRetry(ctx, header.Number)
```
Comment (epociask) [inline internal/conduit/registry/geth_block.go:200]: Let's loggg here

File: internal/conduit/registry/geth_block_test.go [hunk 11]
```diff
@@ -0,0 +1,341 @@
...
+
+				ctx, cancel := context.WithCancel(context.Background())
+				defer cancel()
+
+				err := od.BackTestRoutine(ctx, outChan, big.NewInt(2), big.NewInt(1))
+				assert.Error(t, err)
+				assert.EqualError(t, err, "start height cannot be more than the end height")
+			},
+		},
+		//{
```
Comment (epociask) [inline internal/conduit/registry/geth_block_test.go:115]: Why are we commenting these out?

File: internal/conduit/pipeline/eth_client.go [hunk 12]
```diff
@@ -0,0 +1,38 @@
+package pipeline
```
[the remark this answers is not in the document]
Comment (anupsv-cb) [reply internal/conduit/pipeline/eth_client.go:1]: Done

File: internal/conduit/pipeline/eth_client.go (hunk 1 above)
Comment (anupsv-cb) [reply internal/conduit/pipeline/eth_client.go:2]: Created #20

File: internal/conduit/registry/geth_block.go (hunk 4 above)
Comment (anupsv-cb) [reply internal/conduit/registry/geth_block.go:24]: fixed

File: internal/conduit/registry/geth_block.go (hunk 8 above)
Comment (anupsv-cb) [reply internal/conduit/registry/geth_block.go:175]: Created #21

File: internal/conduit/registry/geth_block.go (hunk 9 above)
Comment (anupsv-cb) [reply internal/conduit/registry/geth_block.go:198]: fixed

File: internal/conduit/registry/geth_block_test.go (hunk 11 above)
Comment (anupsv-cb) [reply internal/conduit/registry/geth_block_test.go:115]: added reason

File: internal/conduit/pipeline/oracle.go (hunk 2 above)
Comment (anupsv-cb) [reply internal/conduit/pipeline/oracle.go:70]: Created #22

File: internal/conduit/models/constants.go [hunk 13]
```diff
@@ -8,3 +8,16 @@ const (
...
 	Conveyor ComponentType = 2
 )
+
+type FetchType int
+
+const (
+	FetchHeader FetchType = 0
+	FetchBlock  FetchType = 1
+)
+
```
Comment (epociask) [inline internal/conduit/models/constants.go:18]: Ooooo

File: internal/conduit/pipeline/oracle.go [hunk 14]
```diff
@@ -45,29 +49,38 @@ func NewOracle(ctx context.Context, ot OracleType,
...
 		opt(o)
 	}
 
-	if cfgErr := od.ConfigureRoutine(ctx); cfgErr != nil {
+	if cfgErr := od.ConfigureRoutine(); cfgErr != nil {
 		return nil, cfgErr
 	}
 
 	return o, nil
 }
```
Comment (epociask) [inline internal/conduit/pipeline/oracle.go:66]:
```suggestion
// TODO (#22) : Add closure logic to all component types 
```

File: internal/conduit/registry/geth_block.go [hunk 15]
```diff
@@ -18,82 +21,201 @@ const (
...
+	for {
+		select {
+		case <-ticker.C:
+
+			headerAsInterface, err := oracle.fetchData(ctx, height, models.FetchHeader)
+			headerAsserted, headerAssertedOk := headerAsInterface.(*types.Header)
+			// means the above retries failed
+			if err != nil || !headerAssertedOk {
+				log.Error("problem fetching header", zap.Error(err))
+
```
Comment (epociask) [inline internal/conduit/registry/geth_block.go:92]: In the case where `err = nil && headerAssertedOk == false`; we'd output:
```
{"msg": "problem fetching header", "error": nil }
```

Maybe want to add a specific message or error for a failed type assertion.

File: internal/client/eth_client.go [hunk 16]
```diff
@@ -0,0 +1,38 @@
+package client
+
+import (
+	"context"
+	"math/big"
+
+	"github.com/ethereum/go-ethereum/core/types"
+	"github.com/ethereum/go-ethereum/ethclient"
+)
+
```
Comment (epociask) [inline internal/client/eth_client.go:10]:
```suggestion

// TODO (#20) : Introduce optional Retry-able EthClient

File: internal/conduit/registry/geth_block.go [hunk 17]
```diff
@@ -18,82 +21,201 @@ const (
```
Comment (epociask) [inline internal/conduit/registry/geth_block.go:21]:
```suggestion

// TODO(#21): Verify config validity during Oracle construction
```

**Comment by epociask** [comment]
@anupsv-cb reviewed, we should be good to go after this round though. Thank you for you contributions sir!

File: internal/conduit/registry/geth_block.go (hunk 15 above)
Comment (anupsv-cb) [reply internal/conduit/registry/geth_block.go]: Ah fixed it. Logged both probable errors since type assertion only returns bool.

**Review by epociask — APPROVED** [review]
LGTM
