### PR TITLE
Granular Health Checks

### LINKED ISSUE #77: More Granular Health Checking
## Problem
The existing health checking `/health` endpoint performs no real health assessment. It fails to consider dependency health (Ie. layer-1 node, layer-2 node, slack), meaning that Pessimism will render `Healthy=true` in the event of upstream node/dependency failures. 

## Problem Solution
The health check `/health` endpoint should be extended to support health checking assessments for critical application dependencies. Starting out, the health check struct itself should look something like:
```
type HealthCheck {
      IsL1Healthy bool
      IsL2Healthy bool
}
``` 

From there, the yielded `Healthy` value in the client response should return:
```
 true if IsL1Healthy == true && IsL2Healthy == true
 false if IsL1Healthy != true || IsL2Healthy != true

```

### PR DESCRIPTION
**Pull request by a-drain**
Closes #77 

## Fixes Issue

Fixes #

### CODE REVIEW

File: internal/api/models/health.go [hunk 1]
```diff
@@ -10,3 +10,9 @@ type HealthCheck struct {
 	Timestamp time.Time
 	Healthy   bool
 }
+
+// NodeConnectionStatus ... Used to display health status of each node connection
+type NodeConnectionStatus struct {
```
Comment (epociask) [inline internal/api/models/health.go:15]: I feel like this may be a better name:
```suggestion
type BedrockConnectionStatus struct {
```
 Versus 'NodeConnectionStatus' which implies only a single node.

Comment (epociask) [reply internal/api/models/health.go:15]: Or if we want to be more general, we can call it 'ChainConnectionStatus'

File: internal/api/service/health.go [hunk 2]
```diff
@@ -4,10 +4,37 @@ import (
...
 	"github.com/base-org/pessimism/internal/api/models"
+	"github.com/base-org/pessimism/internal/logging"
+	"go.uber.org/zap"
 )
 
 // CheckHealth ... Returns health check for server
-// NOTE - As of now, this is a hardcoded function
 func (svc *PessimismService) CheckHealth() *models.HealthCheck {
-	return &models.HealthCheck{Timestamp: time.Now(), Healthy: true}
+	healthCheck := &models.NodeConnectionStatus{}
```
Comment (epociask) [inline internal/api/service/health.go:13]: Let's use 'hc' instead of 'healthCheck' to make this function less verbose

File: internal/api/service/health.go [hunk 3]
```diff
@@ -4,10 +4,37 @@ import (
...
+
+	healthCheck.IsL1Healthy = svc.CheckETHRPCHealth(svc.cfg.L1RpcEndpoint)
+	healthCheck.IsL2Healthy = svc.CheckETHRPCHealth(svc.cfg.L2RpcEndpoint)
+
+	healthy := healthCheck.IsL1Healthy && healthCheck.IsL2Healthy
+
+	return &models.HealthCheck{Timestamp: time.Now(), Healthy: healthy}
```
Comment (epociask) [inline internal/api/service/health.go:20]: We may wanna display/embed the application dependencies that are failing into the response object

File: internal/api/service/health.go [hunk 4]
```diff
@@ -4,10 +4,37 @@ import (
...
+func (svc *PessimismService) CheckETHRPCHealth(url string) bool {
+	logger := logging.WithContext(svc.ctx)
+
+	err := svc.ethClient.DialContext(svc.ctx, url)
+	if err != nil {
+		logger.Error("error conntecting to %s", zap.String("url", url))
+		return false
+	}
+
+	_, err = svc.ethClient.HeaderByNumber(svc.ctx, nil)
```
Comment (epociask) [inline internal/api/service/health.go:32]: I almost wonder if just being able to dial a connection would be sufficient enough. Grabbing the block header may be erroneous given that we aren't actually using it for anything. The only thing that comes to mind is validating that the chain is continuously producing new blocks. That would however be out of scope for this health checking endpoint.

File: internal/api/service/service.go [hunk 5]
```diff
@@ -18,6 +19,7 @@ type Config struct {
 	L2RpcEndpoint  string
 	L1PollInterval int
 	L2PollInterval int
+	SlackURL       string
```
Comment (epociask) [inline internal/api/service/service.go:22]: Do we intend to do anything with this value? We may just wanna rm it for the time being

File: internal/api/service/health.go (hunk 4 above)
Comment (a-drain) [reply internal/api/service/health.go:32]: Tested this locally by removing the call to getHeaderByNumber and running the app then turning off wifi and it always returns true when we just check that the DialContext call doesn't fail. Not sure why this is happening, but this is why I initially added a secondary call to get data from the connection

Comment (a-drain) [reply internal/api/service/health.go:32]: Tested this locally by removing the call to getHeaderByNumber and running the app then turning off wifi and it always returns true when we just check that the DialContext call doesn't fail. Not sure why this is happening, but this is why I initially added a secondary call to get data from the connection

Comment (epociask) [reply internal/api/service/health.go:36]: Ah you are correct, looking at the rpc logic in [geth](https://github.com/ethereum/go-ethereum/blob/master/rpc/client.go#L174-L184), this method just appears to be initializing metadata and performs no actual node RPC queries.

Comment (epociask) [reply internal/api/service/health.go:36]: Resolving in the meantime!

**Review by epociask — APPROVED** [review]
LGTM - Only callout is that we still don't have E2E tests to sufficiently verify correctness of this endpoint logic on an application instance.
